# List experiment stages, i.e., the jobs to be run
stages:
  # eval läuft nicht mit torch 2.6.0
  # import_models:
  #   wdir: ..
  #   cmd: FP16=0 python radioml/import_models.py
  #   outs:
  #     - inputs/radioml/model_brevitas_1_simpl.onnx
  #     - inputs/radioml/model_brevitas_1.onnx
  measure_32FP:
    wdir: ..
    cmd: FP16=0 python radioml/measure.py
    deps:
      - inputs/radioml/model_dynamic_batchsize.onnx
      - radioml/measure.py
    params:
      - radioml/params.yaml:
          - batch_sizes
    plots:
     -  outputs/radioml/throughput/FP32/throughput_results.json:
         template: plot_templates/bar_2.json
         x: batch_size
         y: throughput_batches_per_s
         cache: false
     - outputs/radioml/throughput/FP32/throughput_results_2.json:
         template: plot_templates/bar_1.json
         x: batch_size
         y: throughput_images_per_s
         cache: false
     - outputs/radioml/throughput/FP32/latency_results.json:
         template: plot_templates/bar_3.json
         x: batch_size
         y: value
         cache: false
     - outputs/radioml/throughput/FP32/latency_results_batch.json:
         template: plot_templates/bar_4.json
         x: batch_size
         y: value
         cache: false
  plot_32FP:
    wdir: ..
    cmd: python radioml/latency_throughput_log.py
    deps:
      - radioml/latency_throughput_log.py
      - outputs/radioml/throughput/FP32/latency_results_batch.json
      - outputs/radioml/throughput/FP32/throughput_results.json
    plots:
      - outputs/radioml/throughput/FP32/latency_throughput.json:
          template: plot_templates/latency_throughput.json
          x: latency_total
          y: throughput_images_per_s
          cache: false

  measure_16FP:
    wdir: ..
    cmd: FP16=1 python radioml/measure.py
    deps:
      - inputs/radioml/model_dynamic_batchsize.onnx
      - radioml/measure.py
    params:
      - radioml/params.yaml:
          - batch_sizes
    plots:
     -  outputs/radioml/throughput/FP16/throughput_results.json:
         template: plot_templates/bar_2_FP16.json
         x: batch_size
         y: throughput_batches_per_s
         cache: false
     - outputs/radioml/throughput/FP16/throughput_results_2.json:
         template: plot_templates/bar_1_FP16.json
         x: batch_size
         y: throughput_images_per_s
         cache: false
     - outputs/radioml/throughput/FP16/latency_results.json:
         template: plot_templates/bar_3_FP16.json
         x: batch_size
         y: value
         cache: false
     - outputs/radioml/throughput/FP16/latency_results_batch.json:
         template: plot_templates/bar_4_FP16.json
         x: batch_size
         y: value
         cache: false
  measure_INT8_brevitas:
    wdir: ..
    cmd: INT8=1 python radioml/measure.py
    deps:
      - radioml/measure.py
      - plot_templates/bar_1_INT8.json
      - plot_templates/bar_2_INT8.json
      - plot_templates/bar_3_INT8.json
      - plot_templates/bar_4_INT8.json
    params:
      - radioml/params.yaml:
          - batch_sizes
    outs:
      - outputs/radioml/eval_results/accuracy_INT8.json
    plots:
     -  outputs/radioml/throughput/INT8/throughput_results.json:
         template: plot_templates/bar_2_INT8.json
         x: batch_size
         y: throughput_batches_per_s
         cache: false
     - outputs/radioml/throughput/INT8/throughput_results_2.json:
         template: plot_templates/bar_1_INT8.json
         x: batch_size
         y: throughput_images_per_s
         cache: false
     - outputs/radioml/throughput/INT8/latency_results.json:
         template: plot_templates/bar_3_INT8.json
         x: batch_size
         y: value
         cache: false
     - outputs/radioml/throughput/INT8/latency_results_batch.json:
         template: plot_templates/bar_4_INT8.json
         x: batch_size
         y: value
         cache: false
  accuracy_comparison:
    wdir: ..
    cmd: python radioml/accuracy_comparison.py
    deps:
      - radioml/accuracy_comparison.py
      - outputs/radioml/eval_results/accuracy_FP32.json
      - outputs/radioml/eval_results/accuracy_FP16.json
      - outputs/radioml/eval_results/accuracy_INT8.json
    params:
      - radioml/params.yaml:
          - batch_sizes
    plots:
     -  outputs/radioml/eval_results/accuracy.json:
         template: plot_templates/bar_accuracy.json
         x: quantisation_type
         y: value
         cache: false
  energy_measure_FP32:
    wdir: ..
    cmd: python radioml/tegrastats.py
    deps:
      - radioml/tegrastats.py
      - radioml/parse_tegrastats_to_json.py
      - radioml/power_averages.py
    params:
      - radioml/params.yaml:
          - batch_sizes
    outs:
      - outputs/radioml/energy_metrics/energy_metrics.json
      - outputs/radioml/energy_metrics/ram_metrics_2.json
      - outputs/radioml/energy_metrics/energy_consumption_2.json
    plots:
     -  outputs/radioml/energy_metrics/ram_metrics.json:
          template: plot_templates/ram_used.json
          x: timestamp
          y: ram_used
          cache: false
     -  outputs/radioml/energy_metrics/energy_consumption.json:
          template: plot_templates/energy_consumption.json
          x: timestamp
          y: value
          cache: false
     - outputs/radioml/energy_metrics/power_averages.json:
          template: plot_templates/power_averages.json
          x: batch_size
          y: value
          cache: false
     - outputs/radioml/energy_metrics/power_averages_baseline.json:
          template: plot_templates/power_averages_baseline.json
          x: batch_size
          y: value
          cache: false
     - outputs/radioml/energy_metrics/power_averages_difference.json:
          template: plot_templates/power_averages_difference.json
          x: batch_size
          y: value
          cache: false
